### ISSUE TITLE
--debug option is not available in onnx-mlir and onnx-mlir-opt

### ISSUE THREAD

**Issue by tungld** [onnx/onnx-mlir#2473]
With the current commit, there is no `--debug` option in commands: `onnx-mlir` and `onnx-mlir-opt`.

```shell
./Debug/bin/onnx-mlir --debug
onnx-mlir: Unknown command line argument '--debug'.  Try: './Debug/bin/onnx-mlir --help'
onnx-mlir: Did you mean '--tag'?
Failed to parse options
```

**Comment by sorenlassen** [comment]
I tried commenting out the call to `removeUnrelatedOptions()` in onnx-mlir and onnx-mlir-opt and then `--debug` works again

cc @gongsu832

**Comment by gongsu832** [comment]
`--debug` is some kind of internal option? It's not even listed in `--help`.

**Comment by gongsu832** [comment]
`--debug` is some kind of internal option? It's not listed in `CompilerOptions.cpp`.

**Comment by tungld** [comment]
It's an MLIR option to enable things printed by `LLVM_DEBUG()`.  We would like to have it when onnx-mlir is built with Debug mode, because it is important for debugging. Having it with Release mode would not make sense.

**Comment by gongsu832** [comment]
How is it enabled? Why does it not appear in `--help`?

**Comment by tungld** [comment]
> How is it enabled? Why does it not appear in --help?

I have no idea on this.

**Comment by sorenlassen** [comment]
I believe that it's defined (in an unusual way) here:
https://github.com/llvm/llvm-project/blob/main/llvm/lib/Support/Debug.cpp#L87

it doesn't appear in `mlir-opt --help` either, maybe because it's defined with `cl::Hidden`?

it's the same with `-debug-only` and `-debug-buffer-size`

**Comment by gongsu832** [comment]
PR https://github.com/onnx/onnx-mlir/pull/2475 should fix this.

**Comment by sorenlassen** [comment]
> It looks like `llvm::initDebugOptions()` is to enable it

actually, onnx-mlir and onnx-mlir-opt call that indirectly via `llvm::cl::ParseCommandLineOptions()`

that doesn't solve the problem because it's also called indirectly via `llvm::cl::HideUnrelatedOptions()` which is called at the beginning of `onnx_mlir::removeUnrelatedOptions()`, which makes the subsequent call do nothing as the first call did the static initialization

I discovered this by running onnx-mlir-opt in a debugger with a breakpoint at `llvm::initDebugOptions()`

**Comment by gongsu832** [comment]
> > It looks like `llvm::initDebugOptions()` is to enable it
> 
> actually, onnx-mlir and onnx-mlir-opt call that indirectly via `llvm::cl::ParseCommandLineOptions()`
> 
> that doesn't solve the problem because it's also called indirectly via `llvm::cl::HideUnrelatedOptions()` which is called at the beginning of `onnx_mlir::removeUnrelatedOptions()`, which makes the subsequent call do nothing as the first call did the static initialization
> 
> I discovered this by running onnx-mlir-opt in a debugger with a breakpoint at `llvm::initDebugOptions()`

Are you saying the fix doesn't work for you? It works for me.

**Comment by gongsu832** [comment]
OK the general options like `--debug` were working but not showing up with `--help[-list]-hidden`. That has been fixed.

**Comment by sorenlassen** [comment]
> Are you saying the fix doesn't work for you?

no, I had overlooked your fix when I posted my comment

your fix looks good, I approved it

**Comment by sorenlassen** [comment]
closing this because this was solved by PR #2475
