### ISSUE TITLE
Failed to build on OSX

### ISSUE THREAD

**Issue by yongwww** [onnx/onnx-mlir#388]
Followed the guide to build this project on my local Mac, failed with "CMake Error at MLIR.cmake:136 (message):
  MLIRMlirOptMain not found, did you forget to build llvm-project?"

**Comment by yongwww** [comment]
Tried to comment MLIRMlirOptMain in cmakelist.txt, got issues like this when executing `cmake --build .`: 

```
src/Runtime/jni/jniwrapper.c:304:9: error: implicit declaration of function 'omt_getDataBufferSize' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        omt_getDataBufferSize(jni_omts[i]), 0, env, japi->ecpt_cls,
...
src/Runtime/jni/jniwrapper.c:308:41: error: implicit declaration of function 'omTensorGetName' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    LIB_TYPE_VAR_CALL(char *, jni_name, omTensorGetName(jni_omts[i]), NULL, env,
...

```

**Comment by yongwww** [comment]
"MLIRMlirOptMain not found" happens even I built with Ubuntu on AWS EC2 C5 instance

**Comment by doru1004** [comment]
Are you using the version of LLVM that is mentioned in the README? Make sure that it's getting picked up instead of some other LLVM project version.

**Comment by tjingrant** [comment]
And regarding the implicit declaration errors, it's being addressed in this patch (https://github.com/onnx/onnx-mlir/pull/384).

**Comment by yongwww** [comment]
> Are you using the version of LLVM that is mentioned in the README? Make sure that it's getting picked up instead of some other LLVM project version that you may have on your system.

yes, I followed the guide in the README, used the llvm commit mentioned in README, and set env. variable LLVM_PROJ_SRC and LLVM_PROJ_BUILD to point to the llvm project.

**Comment by yongwww** [comment]
"MLIRMlirOptMain not found" issue persists. And got a new issue as following at the end (98%) of cmake build.

```
UNREACHABLE executed at ~/onnx-mlir/src/MainUtils.cpp:157!
Abort trap: 6
```

ran into the same error when executing `~/build/bin/onnx-mlir ~/build/test/unit/Runtime/DocExampleTest/add.onnx`

**Comment by doru1004** [comment]
Cab you make sure you're on the latest version of onnx-mlir master?

**Comment by yongwww** [comment]
> Cab you make sure you're on the latest version of onnx-mlir master?

yes, just tried with the latest version of master (commit: 414d702ac4909c657eadb19340d08506272785b5). Got the same error "MLIRMlirOptMain not found"

**Comment by sstamenova** [comment]
Recently the way the cmake files from mlir are imported into onnx-mlir was updated and the build on any platform llvm and onnx-mlir support should be green. Can you check if this is still an issue?
